// The Smart Design Template Engine's library.
// This is intentionally NOT generative AI: it is a curated library of
// professionally designed templates, matched to a VA's plain-text prompt
// by keyword scoring (see match-template.ts). Every result is a real,
// pre-built template with text/image "slots" filled in from the prompt —
// never a generated image. Keep the UI copy honest about that ("Smart
// Templates", "matched instantly from our library") — see MEMORY / the
// product brief for why.

export type TemplateCategory =
  | "Logo"
  | "Social Post"
  | "Flyer"
  | "Business Card"
  | "Presentation";

export interface DesignTemplate {
  id: string;
  name: string;
  category: TemplateCategory;
  /** Lowercase keywords this template matches against a prompt. */
  keywords: string[];
  /** Hue (0-360) used to render this template's placeholder art in an OKLCH accent. */
  hue: number;
  /** A single inline-SVG path (24x24 viewBox, stroke-based) used as the template's accent glyph. */
  iconPath: string;
  /** Sample headline copy shown in the thumbnail preview (brand name for Logo, person's name for Business Card, title for Presentation). */
  headline: string;
  /** Sample supporting copy (role/title, subtitle, or a second line). */
  sub?: string;
  /** Small pill/badge copy shown on Social Post and Flyer previews. */
  tag?: string;
}

export const designTemplates: DesignTemplate[] = [
  // --- Logo ---
  {
    id: "logo-minimal-mark",
    name: "Minimal Mark",
    category: "Logo",
    keywords: ["logo", "brand", "mark", "minimal", "simple", "icon"],
    hue: 150,
    iconPath: "M12 6v12M6 12h12 M12 12m-6 0a6 6 0 1 0 12 0a6 6 0 1 0 -12 0",
    headline: "BRIGHTLEAF",
  },
  {
    id: "logo-emblem-badge",
    name: "Emblem Badge",
    category: "Logo",
    keywords: ["logo", "badge", "emblem", "crest", "gym", "fitness", "club", "sports"],
    hue: 120,
    iconPath: "M12 3l7 4v6c0 4-3 7-7 8-4-1-7-4-7-8V7Z",
    headline: "VANTAGE FITNESS",
  },
  {
    id: "logo-wordmark",
    name: "Bold Wordmark",
    category: "Logo",
    keywords: ["logo", "wordmark", "text", "typography", "name", "studio"],
    hue: 30,
    iconPath: "M4 18V6h4l4 8 4-8h4v12",
    headline: "STUDIO",
  },
  {
    id: "logo-monogram",
    name: "Monogram",
    category: "Logo",
    keywords: ["logo", "monogram", "initials", "letter", "law", "firm", "professional"],
    hue: 255,
    iconPath: "M6 18V6h6a4 4 0 0 1 0 8H6 M12 14l6 4",
    headline: "M & F LAW",
  },
  {
    id: "logo-geometric-icon",
    name: "Geometric Icon",
    category: "Logo",
    keywords: ["logo", "geometric", "abstract", "hexagon", "tech", "modern"],
    hue: 190,
    iconPath: "M12 3l7.5 4.5v9L12 21l-7.5-4.5v-9Z",
    headline: "HEXAGON CO",
  },
  {
    id: "logo-nature-mark",
    name: "Nature Mark",
    category: "Logo",
    keywords: ["logo", "nature", "leaf", "organic", "eco", "plant", "garden", "wellness"],
    hue: 95,
    iconPath: "M6 20c8 0 12-6 12-14-8 0-12 6-12 14Z M6 20c2-4 5-7 9-9",
    headline: "EVERGREEN",
  },
  {
    id: "logo-circuit-tech",
    name: "Circuit Tech",
    category: "Logo",
    keywords: ["logo", "tech", "startup", "software", "app", "digital"],
    hue: 220,
    iconPath: "M7 7m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0 M17 17m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0 M9.5 9.5l5 5",
    headline: "NODE LABS",
  },
  {
    id: "logo-star-emblem",
    name: "Star Emblem",
    category: "Logo",
    keywords: ["logo", "star", "premium", "award", "excellence", "five star"],
    hue: 45,
    iconPath: "M12 3l2.6 5.6 6.1.6-4.6 4.1 1.3 6-5.4-3.1-5.4 3.1 1.3-6-4.6-4.1 6.1-.6Z",
    headline: "STARLIGHT",
  },

  // --- Social Post ---
  {
    id: "social-bold-announcement",
    name: "Bold Announcement",
    category: "Social Post",
    keywords: ["announcement", "instagram", "post", "menu", "launch", "new", "bakery"],
    hue: 340,
    iconPath: "M4 15l4-4 4 4 3-3 5 5 M3 4h18v13H3Z",
    headline: "Fall menu is here",
    sub: "Try our new seasonal favorites",
    tag: "NEW",
  },
  {
    id: "social-seasonal-promo",
    name: "Seasonal Promo",
    category: "Social Post",
    keywords: ["seasonal", "sale", "promo", "discount", "fall", "holiday", "summer", "instagram"],
    hue: 200,
    iconPath: "M3 12l4-8 4 8 4-8 4 8 M3 17h18",
    headline: "20% off this week",
    sub: "Online & in-store",
    tag: "SALE",
  },
  {
    id: "social-quote-card",
    name: "Quote Card",
    category: "Social Post",
    keywords: ["quote", "testimonial", "review", "instagram", "post", "inspiration"],
    hue: 280,
    iconPath: "M7 8c-2 0-3 1.5-3 3.5S5 15 7 15 M7 15v3 M17 8c-2 0-3 1.5-3 3.5s1 3.5 3 3.5 M17 15v3",
    headline: "“Small business, big heart.”",
    sub: "— a happy customer",
    tag: "REVIEW",
  },
  {
    id: "social-event-invite",
    name: "Community Event",
    category: "Social Post",
    keywords: ["event", "invite", "community", "meetup", "class", "workshop"],
    hue: 340,
    iconPath: "M8 9a2.5 2.5 0 1 1 0 0.01Z M16 9a2.5 2.5 0 1 1 0 0.01Z M4 19c0-3 2.5-5 4-5 M20 19c0-3-2.5-5-4-5",
    headline: "You're invited",
    sub: "Sat, Oct 4 · 10am",
    tag: "RSVP",
  },
  {
    id: "social-product-spotlight",
    name: "Product Spotlight",
    category: "Social Post",
    keywords: ["product", "spotlight", "feature", "showcase", "new arrival"],
    hue: 25,
    iconPath: "M12 8a4 4 0 1 0 0 8a4 4 0 1 0 0-8Z M12 2v2M12 20v2M4 12H2M22 12h-2M5 5l1.5 1.5M17.5 17.5 19 19M19 5l-1.5 1.5M6.5 17.5 5 19",
    headline: "Now available",
    sub: "Meet our newest arrival",
    tag: "FEATURED",
  },
  {
    id: "social-before-after",
    name: "Before & After",
    category: "Social Post",
    keywords: ["before after", "transform", "results", "makeover"],
    hue: 165,
    iconPath: "M3 12h8M3 12l3-3M3 12l3 3 M21 12h-8M21 12l-3-3M21 12l-3 3",
    headline: "See the difference",
    sub: "Real results, real clients",
    tag: "RESULTS",
  },
  {
    id: "social-countdown",
    name: "Countdown",
    category: "Social Post",
    keywords: ["countdown", "limited", "hurry", "ends soon", "deadline"],
    hue: 15,
    iconPath: "M6 2h12M6 22h12M6 2c0 6 4 6 4 10s-4 4-4 10M18 2c0 6-4 6-4 10s4 4 4 10",
    headline: "2 days left",
    sub: "Offer ends Sunday",
    tag: "HURRY",
  },
  {
    id: "social-tip-of-day",
    name: "Tip of the Day",
    category: "Social Post",
    keywords: ["tip", "advice", "how to", "guide", "education"],
    hue: 205,
    iconPath: "M9 18h6M10 21h4M12 3a6 6 0 0 0-3 11.2c.6.4 1 1.1 1 1.8h4c0-.7.4-1.4 1-1.8A6 6 0 0 0 12 3Z",
    headline: "Tip of the day",
    sub: "Simple tricks, better results",
    tag: "TIP",
  },

  // --- Flyer ---
  {
    id: "flyer-grand-opening",
    name: "Grand Opening Sale",
    category: "Flyer",
    keywords: ["flyer", "opening", "sale", "new", "store", "shop", "launch"],
    hue: 55,
    iconPath: "M4 20V9l8-5 8 5v11 M9 20v-6h6v6",
    headline: "Grand Opening",
    sub: "This weekend only",
    tag: "SAT–SUN",
  },
  {
    id: "flyer-open-house",
    name: "Open House",
    category: "Flyer",
    keywords: ["flyer", "open house", "real estate", "realty", "property", "home", "listing"],
    hue: 200,
    iconPath: "M3 11l9-7 9 7 M5 10v9h14v-9",
    headline: "Open House",
    sub: "3 bed · 2 bath · downtown",
    tag: "SUN 1–4PM",
  },
  {
    id: "flyer-community-event",
    name: "Fall Festival",
    category: "Flyer",
    keywords: ["flyer", "event", "community", "fundraiser", "festival"],
    hue: 340,
    iconPath: "M8 9a2.5 2.5 0 1 1 0 0.01Z M16 9a2.5 2.5 0 1 1 0 0.01Z M4 19c0-3 2.5-5 4-5 M20 19c0-3-2.5-5-4-5",
    headline: "Fall Festival",
    sub: "Food, music & family fun",
    tag: "OCT 12",
  },
  {
    id: "flyer-class-workshop",
    name: "Class & Workshop",
    category: "Flyer",
    keywords: ["flyer", "class", "workshop", "training", "session", "fitness", "studio"],
    hue: 120,
    iconPath: "M4 6h16v10H4Z M8 20h8 M12 16v4",
    headline: "New Member Class",
    sub: "All levels welcome",
    tag: "MON 6PM",
  },
  {
    id: "flyer-holiday-sale",
    name: "Holiday Sale",
    category: "Flyer",
    keywords: ["holiday", "christmas", "sale", "gift", "seasonal"],
    hue: 355,
    iconPath: "M4 8h16v13H4Z M4 8V5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3M12 8v13",
    headline: "Holiday Sale",
    sub: "Up to 40% off storewide",
    tag: "DEC 1–24",
  },
  {
    id: "flyer-menu-special",
    name: "Menu Special",
    category: "Flyer",
    keywords: ["menu", "restaurant", "food", "special", "cafe"],
    hue: 35,
    iconPath: "M8 2v8a2 2 0 0 0 4 0V2M10 10v12M16 2c-1 2-1 4 0 6v12",
    headline: "Weekend Special",
    sub: "Chef's new seasonal plate",
    tag: "FRI–SUN",
  },
  {
    id: "flyer-fundraiser",
    name: "Fundraiser",
    category: "Flyer",
    keywords: ["fundraiser", "charity", "donate", "nonprofit", "cause"],
    hue: 350,
    iconPath: "M12 21s-7-4.4-9.5-9A5 5 0 0 1 12 6a5 5 0 0 1 9.5 6c-2.5 4.6-9.5 9-9.5 9Z",
    headline: "Help Us Give Back",
    sub: "Every dollar makes a difference",
    tag: "DONATE",
  },
  {
    id: "flyer-job-opening",
    name: "Job Opening",
    category: "Flyer",
    keywords: ["hiring", "job", "career", "now hiring", "join our team"],
    hue: 215,
    iconPath: "M4 8h16v11H4Z M9 8V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v3M4 13h16",
    headline: "Now Hiring",
    sub: "Join our growing team",
    tag: "APPLY TODAY",
  },

  // --- Business Card ---
  {
    id: "card-modern-contact",
    name: "Modern Contact Card",
    category: "Business Card",
    keywords: ["business card", "card", "contact", "modern"],
    hue: 265,
    iconPath: "M3 6h18v12H3Z M7 15h4",
    headline: "Jordan Blake",
    sub: "Creative Director",
  },
  {
    id: "card-minimal-line",
    name: "Minimal Line",
    category: "Business Card",
    keywords: ["business card", "card", "minimal", "clean"],
    hue: 150,
    iconPath: "M3 6h18v12H3Z M6 10h12 M6 14h6",
    headline: "Sam Rivera",
    sub: "Founder",
  },
  {
    id: "card-law-firm",
    name: "Professional Monogram",
    category: "Business Card",
    keywords: ["business card", "card", "law", "firm", "professional", "attorney"],
    hue: 255,
    iconPath: "M3 6h18v12H3Z M9 15V9h3a2 2 0 0 1 0 4H9",
    headline: "Devon Marlowe",
    sub: "Attorney at Law",
  },
  {
    id: "card-bold-color-block",
    name: "Bold Color Block",
    category: "Business Card",
    keywords: ["business card", "bold", "colorful", "creative", "agency"],
    hue: 20,
    iconPath: "M4 4h6v16H4Z M14 4h6v10h-6Z",
    headline: "Alex Chen",
    sub: "Brand Strategist",
  },
  {
    id: "card-elegant-serif",
    name: "Elegant Serif",
    category: "Business Card",
    keywords: ["business card", "elegant", "luxury", "boutique", "classic"],
    hue: 40,
    iconPath: "M4 20 18 6a2.5 2.5 0 0 0-3.5-3.5L1 16l1 3 3 1Z M15 5l4 4",
    headline: "Isabel Cruz",
    sub: "Boutique Owner",
  },
  {
    id: "card-two-tone-split",
    name: "Two-Tone Split",
    category: "Business Card",
    keywords: ["business card", "two tone", "split", "modern", "corporate"],
    hue: 230,
    iconPath: "M4 4h16v16H4Z M4 4l16 16",
    headline: "Priya Nair",
    sub: "Wellness Coach",
  },

  // --- Presentation ---
  {
    id: "deck-pitch-cover",
    name: "Pitch Deck Cover",
    category: "Presentation",
    keywords: ["presentation", "deck", "pitch", "slides", "cover"],
    hue: 25,
    iconPath: "M3 4h18v13H3Z M8 21h8M12 17v4",
    headline: "The Pitch",
    sub: "Q4 growth strategy",
  },
  {
    id: "deck-quarterly-report",
    name: "Quarterly Report",
    category: "Presentation",
    keywords: ["presentation", "deck", "report", "quarterly", "review", "slides"],
    hue: 200,
    iconPath: "M3 4h18v13H3Z M7 14v-4 M12 14V8 M17 14v-6",
    headline: "Q3 Results",
    sub: "Performance overview",
  },
  {
    id: "deck-onboarding",
    name: "Client Onboarding",
    category: "Presentation",
    keywords: ["presentation", "deck", "onboarding", "welcome", "kickoff", "slides"],
    hue: 340,
    iconPath: "M3 4h18v13H3Z M9 10.5h6 M9 13.5h4",
    headline: "Welcome Aboard",
    sub: "Getting started together",
  },
  {
    id: "deck-team-intro",
    name: "Team Intro",
    category: "Presentation",
    keywords: ["presentation", "team", "about us", "meet the team", "introduction"],
    hue: 165,
    iconPath: "M8 8a3 3 0 1 0 0-6a3 3 0 1 0 0 6ZM16 10a2.5 2.5 0 1 0 0-5a2.5 2.5 0 1 0 0 5Z M2 20c0-3.3 2.7-6 6-6s6 2.7 6 6M14.5 20c.3-2.8 2.2-5 4.5-5.4",
    headline: "Meet the Team",
    sub: "The people behind the work",
  },
  {
    id: "deck-case-study",
    name: "Case Study",
    category: "Presentation",
    keywords: ["presentation", "case study", "results", "success story"],
    hue: 210,
    iconPath: "M11 11m-6 0a6 6 0 1 0 12 0a6 6 0 1 0 -12 0 M21 21l-4.3-4.3 M8 12l2-3 2 2 2-4",
    headline: "Case Study",
    sub: "How we drove real results",
  },
  {
    id: "deck-roadmap",
    name: "Roadmap",
    category: "Presentation",
    keywords: ["presentation", "roadmap", "timeline", "plan", "milestones"],
    hue: 100,
    iconPath: "M3 12h4l2-4 3 8 3-8 2 4h4",
    headline: "The Roadmap",
    sub: "What's next, quarter by quarter",
  },
];

export const templateCategories: TemplateCategory[] = [
  "Logo",
  "Social Post",
  "Flyer",
  "Business Card",
  "Presentation",
];
