"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { clientLogoutAction } from "@/app/client/logout/actions";
import { resetDemoAction } from "@/app/demo/actions";
import styles from "./ClientShell.module.css";

function initialsOf(name: string) {
  return name.split(" ").map((p) => p[0]).join("").slice(0, 2).toUpperCase();
}

const NAV = [
  { href: "/client", label: "Dashboard" },
  { href: "/client/inbox", label: "Messages" },
];

export function ClientShell({
  clientName,
  contactName,
  isDemo = false,
  children,
}: {
  clientName: string;
  contactName: string;
  isDemo?: boolean;
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <div className={styles.wrap}>
      {isDemo && (
        <div className={styles.demoBanner}>
          <span>● You&apos;re viewing a live demo — everything here (design, project, invoice) was generated by an automated VA bot.</span>
          <form action={resetDemoAction}>
            <button className={styles.demoReset} type="submit">Start a new demo</button>
          </form>
        </div>
      )}
      <div className={styles.topbar}>
        <div className={styles.brandrow}>
          <div className={styles.clientmark}>{initialsOf(clientName)}</div>
          <div>
            <div className={styles.clientname}>{clientName}</div>
            <div className={styles.poweredby}>CLIENT PORTAL · POWERED BY VA HUB</div>
          </div>
        </div>
        <div className={styles.right}>
          <nav className={styles.nav}>
            {NAV.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className={`${styles.navlink} ${pathname === item.href ? styles.navlinkOn : ""}`}
              >
                {item.label}
              </Link>
            ))}
          </nav>
          <div className={styles.who}>{contactName}</div>
          <form action={clientLogoutAction}>
            <button className={styles.logout} type="submit">Sign out</button>
          </form>
        </div>
      </div>
      {children}
    </div>
  );
}
